CREATE DATABASE EV_Charging_Analytics;
USE EV_Charging_Analytics;
CREATE TABLE stg_charging_sessions (
    Session_ID VARCHAR(30) PRIMARY KEY,
    Station_ID VARCHAR(20),
    Station_Name VARCHAR(100),
    State VARCHAR(50),
    Charger_Type VARCHAR(50),
    Charger_Power_kW DECIMAL(10,2),
    Vehicle_Type VARCHAR(50),
    Vehicle_Battery_kWh DECIMAL(10,2),
    Battery_Level_Start DECIMAL(5,2),
    Battery_Level_End DECIMAL(5,2),
    Energy_Delivered_kWh DECIMAL(12,2),
    Session_Start DATETIME,
    Session_End DATETIME,
    Session_Duration_Min INT,
    Electricity_Price_per_kWh DECIMAL(10,2),
    Session_Cost DECIMAL(12,2),
    Temperature_C DECIMAL(6,2),
    Weather_Condition VARCHAR(50),
    Peak_Hour VARCHAR(10),
    Queue_Time_Min INT,
    Payment_Method VARCHAR(50),
    Customer_Rating DECIMAL(3,2),
    Revenue_USD DECIMAL(12,2),
    Maintenance_Flag VARCHAR(10),
    Station_Uptime_Percentage DECIMAL(6,2),
    Day_of_Week VARCHAR(20),
    Month INT,
    Holiday_Flag TINYINT,
    Traffic_Index DECIMAL(8,2),
    Renewable_Energy_Percentage DECIMAL(6,2),
    Carbon_Saved_kg DECIMAL(12,2),
    Grid_Load_Percentage DECIMAL(6,2),
    Fast_Charging_Flag TINYINT,
    User_Membership_Type VARCHAR(30),
    Battery_Health_Score DECIMAL(6,2)
);

